# Generated by Django 2.0.1 on 2019-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_auto_20190412_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
