# Generated by Django 2.0.1 on 2019-04-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_auto_20190417_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
