# Generated by Django 2.1.7 on 2019-04-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_auto_20190412_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='item',
        ),
    ]
